add support for trusted fact tags and add info line for puppetserver …
DataDog/puppet-datadog-agent pull request #662
Opened 2020-10-21 23:37 UTC by murdok5

…log notifications

### What does this PR do?

Resolve issue where trusted facts were not working for report fact tags. 

### Motivation

Customer request based on experience/need.

### Additional Notes

Added an unrelated info line to the report processor to log successful sends to Datadog API

### Describe your test plan

Tested in a lab environment using Puppet Enterprise 2019.8.1 with current Datadog.

2020-10-21 23:38 UTC, murdok5 commented
@albertvaka resolved the issues for trusted facts.

2020-10-22 11:50 UTC, albertvaka commented
Thanks a lot! We didn't know this was possible :) To be consistent with https://github.com/DataDog/puppet-datadog-agent/pull/658 I think we want to have a separate argument (eg: `report_trusted_fact_tags`) instead of merging the two hashes, but I will make that change on a separate PR. Your help is super appreciated 🙇

2020-10-22 15:03 UTC, murdok5 commented
@albertvaka either merged or separate works makes sense. The reason I merged into a single hash was user simplicity and trusted is a reserved name so there is not a chance of duplication.

2020-10-22 15:48 UTC, albertvaka commented
Yeah, I agree it's simpler like this, but since I initially added two separate arguments for `facts_to_tags` and `trusted_facts_to_tags` I think this should follow the same pattern with `report_fact_tags` and `report_trusted_fact_tags`.

2020-10-22 15:59 UTC, murdok5 commented
> Yeah, I agree it's simpler like this, but since I initially added two separate arguments for `facts_to_tags` and `trusted_facts_to_tags` I think this should follow the same pattern with `report_fact_tags` and `report_trusted_fact_tags`.

Makes sense to stay consistent with that pattern.

2020-10-22 16:48 UTC, albertvaka commented
I pushed a commit to your branch that should do it, can you give it a quick look before I merge?

2020-10-24 19:58 UTC, murdok5 commented
> I pushed a commit to your branch that should do it, can you give it a quick look before I merge?

Were you able to test this or you do want me to test in my lab?

2020-10-25 11:40 UTC, albertvaka commented
I've tested the Puppet side but not the Ruby script changes.

2020-11-05 19:45 UTC, kayayarai requested changes
Hey there Mike! A couple typo fixes and some formatting to help with documentation readability, in the README.md.

2020-11-05 19:45 UTC, kayayarai commented on README.md
> +    You can add tags to reports that are sent to Datadog as events. These tags can be sourced from Puppet facts for the given node the report is regarding. These should be 1:1 and not involve structu
```suggestion
    You can add tags to reports that are sent to Datadog as events. These tags can be sourced from Puppet facts for the given node the report is regarding. These should be 1:1 and not involve structured facts (hashes, arrays, etc.) to ensure readability. 
    To enable regular fact tagging, set the parameter `datadog_agent::reports::report_fact_tags` to the array value of facts—for example `["virtual","operatingsystem"]`.
    To enable trusted fact tagging, set the parameter `datadog_agent::reports::report_trusted_fact_tags` to the array value of facts—for example `["trusted.certname","trusted.extensions.pp_role","trusted.hostname"]`.
```

2020-11-05 19:49 UTC, murdok5 commented
@kayayarai @albertvaka sorry for delay but I did some testing and confirmed functionality.  I updated the readme and some debugging if needed as well.  I tried to differentiate between tags for Datadog agents and Report (event) tagging.

2020-11-05 19:56 UTC, kayayarai commented on README.md
> +    You can add tags to reports that are sent to Datadog as events. These tags can be sourced from Puppet facts for the given node the report is regarding. These should be 1:1 and not involve structu
```suggestion
    You can add tags to reports that are sent to Datadog as events. These tags can be sourced from Puppet facts for the given node the report is regarding. These should be 1:1 and not involve structured facts (hashes, arrays, etc.) to ensure readability. To enable regular fact tagging, set the parameter `datadog_agent::reports::report_fact_tags` to the array value of facts—for example `["virtual","operatingsystem"]`. To enable trusted fact tagging, set the parameter `datadog_agent::reports::report_trusted_fact_tags` to the array value of facts—for example `["trusted.certname","trusted.extensions.pp_role","trusted.hostname"]`.
```
missing the dot between trusted and hostname?

2020-11-06 20:25 UTC, albertvaka commented on lib/puppet/reports/datadog_reports.rb
> +    trusted_facts = { "trusted" => trusted_facts.to_h }
To make sure `report_trusted_fact_tags` is consistent with `trusted_facts_to_tags`. When accessing the `$trusted` variable from puppet code, do you have to use the `trusted.*` prefix?

2020-11-06 21:39 UTC, kayayarai approved these changes
👍  for the documentation

2020-11-19 17:27 UTC, albertvaka commented on lib/puppet/reports/datadog_reports.rb
> +    trusted_facts = { "trusted" => trusted_facts.to_h }
From the examples section in Puppet docs [1], it looks like the `trusted` prefix doesn't have to be used when accessing `$trusted`, so I'm going to remove it from this PR and merge it.

[1] https://puppet.com/docs/puppet/5.5/lang_facts_and_builtin_vars.html#examples

2020-11-19 22:13 UTC, merged