DOCS-2275 Lint README
DataDog/puppet-datadog-agent pull request #711
Opened 2021-07-30 21:16 UTC by ruthnaebeck

### What does this PR do?
Lint README to follow documentation [contributing](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md) guidelines

### Motivation
Docs hackday project

### Additional Notes
N/A

### Describe your test plan
N/A

2021-08-02 07:28 UTC, mx-psi approved these changes

2021-08-04 15:33 UTC, kayayarai requested changes

2021-08-04 15:33 UTC, kayayarai commented on README.md
> +The Datadog Puppet module supports Linux and Windows and is compatible with Puppet >= 4.6.x or Puppet Enterprise version >= 2016.4. For detailed information on compatibility, check the module page on
the link text was more accurate before. The link takes you to the Agent module page on the Forge, not just to the Forge.

2021-08-04 15:33 UTC, kayayarai commented on README.md
> +1. Install the [dogapi][3] gem on your system. Restart puppetserver after the gem has been installed.
```suggestion
1. Install the [dogapi][3] gem on your system. Restart puppetserver after the gem is installed.
```

2021-08-04 22:50 UTC, kayayarai commented on README.md
> +The Datadog Puppet module supports Linux and Windows and is compatible with Puppet >= 4.6.x or Puppet Enterprise version >= 2016.4. For detailed information on compatibility, check the module page on
```suggestion
The Datadog Puppet module supports Linux and Windows and is compatible with Puppet >= 4.6.x or Puppet Enterprise version >= 2016.4. For detailed information on compatibility, check the [module page on Puppet Forge][1].
```

2021-08-04 22:50 UTC, kayayarai approved these changes

2021-08-04 22:51 UTC, merged