upgrade pdk version to 3.4
DataDog/puppet-datadog-agent pull request #823
Opened 2024-12-23 09:50 UTC by xenon8

2025-01-27 14:53 UTC, nielstholenaar commented on manifests/init.pp
> +  String $hostname_extraction_regex = undef,
This should be marked as on Optional in order to allow the default undef value.

```suggestion
  Optional[String] $hostname_extraction_regex = undef,
```

2025-01-27 15:07 UTC, xenon8 commented on manifests/integrations/elasticsearch.pp
>      validate_absolute_path($ssl_verify)
I have a issue here, validate_absolute_path no longer exists, however I do not understand why someone would provide a string to essentially a boolean option.

For simplicity could I remove the option to provide a string path? Then make this a breaking change?

2025-01-27 15:11 UTC, nielstholenaar commented on manifests/init.pp
> +  if versioncmp($_agent_major_version, '5') != 0 and versioncmp($_agent_major_version, '6') != 0 and versioncmp($_agent_major_version, '7') != 0 {
This should be reverted, because versioncmp only accepts a String value.

```suggestion
if $_agent_major_version != 5 and $_agent_major_version != 6 and $_agent_major_version != 7 {
```

2025-01-27 15:11 UTC, nielstholenaar commented on manifests/init.pp
> +    if versioncmp($_agent_major_version, '5') == 0 {
This should be reverted, because versioncmp only accepts a String value.

```suggestion
if $_agent_major_version == 5 {
```

2025-01-27 15:16 UTC, xenon8 commented on manifests/init.pp
> +  String $hostname_extraction_regex = undef,
fixed in my last push

2025-01-27 15:17 UTC, nielstholenaar requested changes
Thanks for all the work on the Puppet 8 version.

I'm currently in the process of upgrading our Puppet server and this module was one of the modules that lacked support. I have added some fixes for things I experienced while using your version.

2025-01-27 15:17 UTC, nielstholenaar commented on manifests/init.pp
> +  if versioncmp($_agent_major_version, '5') == 0 {
This should be reverted, because versioncmp only accepts a String value.

```suggestion
if $_agent_major_version == 5 {
```

2025-01-27 15:17 UTC, nielstholenaar commented on manifests/reports.pp
> +  String $hostname_extraction_regex = undef,
```suggestion
  Optional[String] $hostname_extraction_regex = undef,
```

2025-01-27 15:17 UTC, nielstholenaar commented on manifests/reports.pp
> +  String $proxy_http = undef,
```suggestion
  Optional[String] $proxy_http = undef,
```

2025-01-27 15:17 UTC, nielstholenaar commented on manifests/reports.pp
> +  String $proxy_https = undef,
```suggestion
  Optional[String] $proxy_https = undef,
```

2025-01-27 15:18 UTC, xenon8 commented on manifests/init.pp
> +  if versioncmp($_agent_major_version, '5') != 0 and versioncmp($_agent_major_version, '6') != 0 and versioncmp($_agent_major_version, '7') != 0 {
thanks, I will review the rest of these

2025-01-27 15:31 UTC, xenon8 commented on manifests/reports.pp
> +  String $hostname_extraction_regex = undef,
fixed in next push

2025-01-27 15:32 UTC, xenon8 commented on manifests/reports.pp
> +  String $proxy_http = undef,
fixed in next push

2025-01-27 15:32 UTC, xenon8 commented on manifests/reports.pp
> +  String $proxy_https = undef,
fixed in next push

2025-01-27 15:33 UTC, xenon8 commented on manifests/init.pp
> +    if versioncmp($_agent_major_version, '5') == 0 {
fixed in last push

2025-01-27 15:34 UTC, xenon8 commented on manifests/init.pp
> +  if versioncmp($_agent_major_version, '5') == 0 {
fixed in last push

2025-01-27 15:42 UTC, xenon8 commented on manifests/init.pp
> +  if versioncmp($_agent_major_version, '5') != 0 and versioncmp($_agent_major_version, '6') != 0 and versioncmp($_agent_major_version, '7') != 0 {
Many swearwords, looks like the code is like this all over the shop, I am going to have to change a lot of classes 😭

2025-01-28 16:50 UTC, nielstholenaar requested changes

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/php_fpm.pp
> +  String $http_host        = undef,
```suggestion
  Optional[String] $http_host        = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/php_fpm.pp
> +  Array $instances        = undef,
```suggestion
  Optional[Array] $instances        = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/disk.pp
> +  String $all_partitions                         = undef,
```suggestion
  Optional[String] $all_partitions                         = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/disk.pp
> +  String $tag_by_filesystem                      = undef,
```suggestion
  Optional[String] $tag_by_filesystem                      = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $ca_certs  = undef,
```suggestion
  Optional[String] $ca_certs  = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $sitename  = undef,
Sitename is a required parameter, defining a default value of undef should not be allowed.

```suggestion
  String $sitename,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $url       = undef,
Url is a required parameter, defining a default value of undef should not be allowed.

```suggestion
  String $url,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $username  = undef,
```suggestion
  Optional[String] $username  = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  Integer $min_collection_interval = undef,
According to the class documentation the default value should be `15` however it seems that this default is not present in the current version.

Should we correct this?

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  Integer $threshold = undef,
```suggestion
  Optional[Integer] $threshold = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  Integer $window    = undef,
```suggestion
  Optional[Integer] $window    = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $content_match = undef,
```suggestion
  Optional[String] $content_match = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $http_response_status_code = undef,
```suggestion
  Optional[String] $http_response_status_code = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  Integer $days_warning = undef,
```suggestion
  Optional[Integer] $days_warning = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  Integer $days_critical = undef,
```suggestion
  Optional[Integer] $days_critical = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/solr.pp
> +  String $username             = undef,
```suggestion
  Optional[String] $username             = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/solr.pp
> +  String $java_bin_path        = undef,
```suggestion
  Optional[String] $java_bin_path        = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/solr.pp
> +  String $trust_store_path     = undef,
```suggestion
  Optional[String] $trust_store_path     = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/solr.pp
> +  Any $trust_store_password = undef,
```suggestion
  Optional[Any] $trust_store_password = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/solr.pp
> +  Any $password             = undef,
```suggestion
  Optional[Any] $password             = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/ssh.pp
> +  Any $password          = undef,
```suggestion
  Optional[Any] $password          = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/ssh.pp
> +  String $private_key_file  = undef,
```suggestion
  Optional[String] $private_key_file  = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  String $check_name                = undef,
```suggestion
  String $check_name,
```
This a required param and should not be undef.

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  String $host                      = undef,
```suggestion
  String $host,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  String $port                      = undef,
```suggestion
  String $port,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  Integer $threshold                = undef,
```suggestion
  Optional[Integer] $threshold                = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  Integer $window                   = undef,
```suggestion
  Optional[Integer] $window                   = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  Integer $collect_response_time    = undef,
```suggestion
  Optional[Integer] $collect_response_time    = undef,
```

2025-01-28 16:50 UTC, nielstholenaar commented on manifests/integrations/tcp_check.pp
> +  Integer $skip_event               = undef,
```suggestion
  Optional[Integer] $skip_event               = undef,
```

2025-01-28 20:50 UTC, xenon8 commented on manifests/ubuntu.pp
> +        unless  => "@(\"CMD\"/L)
Fixed this, I made a mistake here with the heredocs definition. I have created a new variable to hold it as per the new recommendations. I have also fixed the ubuntu installer class.

2025-01-28 20:51 UTC, xenon8 commented on manifests/integrations/php_fpm.pp
> +  Array $instances        = undef,
Fixed with latest commit

2025-01-28 20:52 UTC, xenon8 commented on manifests/integrations/disk.pp
> +  String $all_partitions                         = undef,
Fixed with latest commit

2025-01-28 20:52 UTC, xenon8 commented on manifests/integrations/disk.pp
> +  String $tag_by_filesystem                      = undef,
Fixed with latest commit

2025-01-28 20:53 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $ca_certs  = undef,
Fixed with latest commit

2025-01-28 20:55 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $sitename  = undef,
fixed with latest commit

2025-01-28 20:56 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $url       = undef,
Fixed with latest commit

2025-01-28 20:56 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $username  = undef,
Fixed with latest commit

2025-01-28 20:57 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  Integer $min_collection_interval = undef,
agreed.  done.

2025-01-28 20:58 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  Integer $threshold = undef,
Fixed with latest commit

2025-01-28 20:58 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  Integer $window    = undef,
Fixed with latest commit

2025-01-28 20:58 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $content_match = undef,
Fixed with latest commit

2025-01-28 20:58 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $http_response_status_code = undef,
Fixed with latest commit

2025-01-28 20:59 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  Integer $days_warning = undef,
Fixed with latest commit

2025-01-28 20:59 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  Integer $days_critical = undef,
Fixed with latest commit

2025-01-28 20:59 UTC, xenon8 commented on manifests/integrations/solr.pp
> +  String $username             = undef,
Fixed with latest commit

2025-01-28 21:00 UTC, xenon8 commented on manifests/integrations/solr.pp
> +  String $java_bin_path        = undef,
Fixed with latest commit

2025-01-28 21:00 UTC, xenon8 commented on manifests/integrations/solr.pp
> +  String $trust_store_path     = undef,
Fixed with latest commit

2025-01-28 21:00 UTC, xenon8 commented on manifests/integrations/solr.pp
> +  Any $password             = undef,
Fixed with latest commit

2025-01-28 21:00 UTC, xenon8 commented on manifests/integrations/ssh.pp
> +  Any $password          = undef,
Fixed with latest commit

2025-01-28 21:01 UTC, xenon8 commented on manifests/integrations/ssh.pp
> +  String $private_key_file  = undef,
Fixed with latest commit

2025-01-28 21:01 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  String $check_name                = undef,
Fixed with latest commit

2025-01-28 21:02 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  String $host                      = undef,
Fixed with latest commit

2025-01-28 21:02 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  Integer $threshold                = undef,
Fixed with latest commit

2025-01-28 21:02 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  Integer $window                   = undef,
Fixed with latest commit

2025-01-28 21:02 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  Integer $collect_response_time    = undef,
Fixed with latest commit

2025-01-28 21:03 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  Integer $skip_event               = undef,
Fixed with latest commit

2025-01-28 21:03 UTC, xenon8 commented on manifests/integrations/tcp_check.pp
> +  String $port                      = undef,
Fixed with latest commit

2025-01-28 21:04 UTC, xenon8 commented on manifests/integrations/php_fpm.pp
> +  String $http_host        = undef,
Fixed with latest commit

2025-02-03 16:23 UTC, fanny-jiang commented on manifests/integrations/elasticsearch.pp
>      validate_absolute_path($ssl_verify)
@xenon8, I've double-checked the elasticsearch integration and the `ssl_verify` option has been replaced with a new option, `tls_verify`, which is a `Boolean` only (see [here](https://github.com/DataDog/integrations-core/blob/84898e543ff849c59aa38dde8f4866c72cec98c3/elastic/datadog_checks/elastic/data/conf.yaml.example#L444-L447)). Let's go ahead and remove the string path option and make this a breaking change.

2025-02-03 20:49 UTC, xenon8 commented on manifests/integrations/elasticsearch.pp
>      validate_absolute_path($ssl_verify)
Excellent, I will look to make this tomorrow :)

2025-02-04 08:09 UTC, xenon8 commented on manifests/integrations/elasticsearch.pp
>      validate_absolute_path($ssl_verify)
updated the files [here](https://github.com/DataDog/puppet-datadog-agent/pull/823/commits/f38805cc9c733ff85d0f1c6083b9f23d5b2d00a1)

2025-02-11 10:49 UTC, nielstholenaar requested changes

2025-02-11 10:49 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $sitename,
```suggestion
  Optional[String] $sitename = undef,
```

This allows multiple instances to be passed.

2025-02-11 10:49 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $url,
```suggestion
  Optional[String] $url = undef,
```

This allows multiple instances to be passed.

2025-02-11 10:52 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $sitename,
@fanny-jiang Please can you review this and check that you are happy.

2025-02-13 14:42 UTC, nielstholenaar commented on manifests/integrations/http_check.pp
> +  String $sitename,
I have also created a pull request with the changes: https://github.com/xenon8/puppet-datadog-agent/pull/7

Feel free to comment, I'm not sure if we need to adjust the docs.

2025-02-13 18:48 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $sitename,
merged :)

2025-02-13 18:48 UTC, xenon8 commented on manifests/integrations/http_check.pp
> +  String $url,
merged in change 7

2025-03-06 09:28 UTC, nielstholenaar approved these changes

2025-03-10 15:23 UTC, fanny-jiang approved these changes
🎉

2025-03-10 18:11 UTC, rtrieu commented on CHANGELOG.md
> +could break existing implementations.
```suggestion
may break existing implementations.
```

2025-03-10 18:14 UTC, rtrieu commented on CHANGELOG.md
> +* [BUGFIX] BREAKING - `datadog_agent::integrations::disk` now expects booleans for `use_mount`, `all_partitions` and `tag_by_filesystem`
```suggestion
* [BUGFIX] BREAKING - `datadog_agent::integrations::disk` now expects booleans for `use_mount`, `all_partitions`, and `tag_by_filesystem`.
```

2025-03-10 18:14 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] Drop support for Puppet 6 and below
```suggestion
* [DEPRECATE] Drop support for Puppet 6 and below.
```

2025-03-10 18:14 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] Drop support for Datadog Agent version 5, including removal of unit tests
```suggestion
* [DEPRECATE] Drop support for Datadog Agent version 5, including removal of unit tests.
```

2025-03-10 18:14 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] Remove `ganglia`, `graphite`, `dogstreams`, `custom_emitters` and `use_curl_http_client` legacy configuration options which are no longer supported since Datadog Agent v6+
```suggestion
* [DEPRECATE] Remove `ganglia`, `graphite`, `dogstreams`, `custom_emitters`, and `use_curl_http_client` legacy configuration options, which are no longer supported since Datadog Agent v6+
```

2025-03-10 18:14 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] Remove support for supplying a string to the `ssl_verify` option on the elasticsearch integration. We now use `tls_verify` which matches core Datadog code.
```suggestion
* [DEPRECATE] Remove support for supplying a string to the `ssl_verify` option on the elasticsearch integration. We now use `tls_verify` which matches core Datadog code.
```

2025-03-10 18:14 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] Remove legacy Jenkins integration
```suggestion
* [DEPRECATE] Remove legacy Jenkins integration
```
```suggestion
* [DEPRECATE] Remove legacy Jenkins integration.
```

2025-03-10 18:15 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] `skip_event` setting on TCP Check class has been removed from DataDog integration (removed since Datadog Agent v6.4+)
```suggestion
* [DEPRECATE] `skip_event` setting on TCP Check class has been removed from the Datadog integration (removed since Datadog Agent v6.4+).
```

2025-03-10 18:16 UTC, rtrieu commented on manifests/integrations/activemq_xml.pp
> +  Boolean $supress_errors             = false,
```suggestion
  Boolean $suppress_errors             = false,
```

2025-03-10 18:18 UTC, rtrieu commented on manifests/integrations/activemq_xml.pp
> +        'supress_errors'       => $supress_errors,
```suggestion
        'suppress_errors'       => $suppress_errors,
```

2025-03-10 19:15 UTC, fanny-jiang commented on manifests/integrations/activemq_xml.pp
> +        'supress_errors'       => $supress_errors,
This suggested change would be a breaking change since it's changing a config option. I'll add a corrected config option in a later release

2025-03-10 19:53 UTC, fanny-jiang commented on CHANGELOG.md
> +* [DEPRECATE] Remove support for supplying a string to the `ssl_verify` option on the elasticsearch integration. We now use `tls_verify` which matches core Datadog code.
I don't see a diff in the suggestion?

2025-03-10 19:54 UTC, fanny-jiang commented on manifests/integrations/activemq_xml.pp
> +        'supress_errors'       => $supress_errors,
Fixed!

2025-03-10 19:55 UTC, rtrieu commented on CHANGELOG.md
> +* [DEPRECATE] Remove support for supplying a string to the `ssl_verify` option on the elasticsearch integration. We now use `tls_verify` which matches core Datadog code.
oops ignore

2025-03-10 19:56 UTC, rtrieu approved these changes
Looks good, thanks!

2025-03-10 20:48 UTC, merged